version: '3.8'

services:
  mongodb:
    image: mongo:latest # Or specify a version like mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: productuser # Replace with your desired username
      MONGO_INITDB_ROOT_PASSWORD: productpass # Replace with a strong password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mongodb_data:
