version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass # Replace with a strong password
      MYSQL_DATABASE: orderdb # Replace with your desired database name
      MYSQL_USER: orderuser # Replace with your desired username
      MYSQL_PASSWORD: password # Replace with your desired user password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      interval: 10s
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    restart: always

volumes:
  db_data:
    driver: local




